### ISSUE TITLE
Does the Vaadin Designer support Vaadin (web)Components?

### ISSUE THREAD

**Issue by fabm22** [vaadin/vaadin-elements#23]
I've found a demo video which seems to point to a 'yes' but it was not very clear.

So I'd like to know : does the Vaadin Designer lets you build with only  web components (Vaadin Components) and particurarly for JavaScript dev only ?  No server side components.

Thanks for clarification

**Comment by jounik** [comment]
Currently, Vaadin Designer is only usable for the Vaadin Framework, so server-side only. It doesn’t work with Web Components, but there have been discussions about doing something like that in a future version. No clear plans yet, though.

Also, these kinds of questions might be better to ask directly on the [Gitter chat](https://gitter.im/vaadin/vaadin-elements), not perhaps as issues :)

**Comment by fabm22** [comment]
Yes indeed I was not sure neither for the place to ask. Anyway, for your answer, that would be great to have a full featured "native web" ide/designer for a cohesive framework like you guys do. Would help give some nobility to pure frontend tech development.

**Comment by jounik** [comment]
Thanks for asking and for the feedback!
