### ISSUE TITLE
vaadin-combo-box focus causes page width to change in certain browsers

### ISSUE THREAD

**Issue by teijo** [vaadin/vaadin-elements#26]
If vaadin-combo-box gets focus, it hides page scroll bar reducing page width on browsers that have non-overlaid scroll bar (e.g. Chrome on Windows and Chromium on Ubuntu, not OS X). Change to page width will align centered content again making the layout jump on each focus and blur.

To test, open https://cdn.vaadin.com/vaadin-elements/master/vaadin-combo-box/demo/ in non-OS X browser and focus any combo box.

**Comment by Saulis** [comment]
Thanks dude! Let's move this under http://github.com/vaadin/vaadin-combo-box :smile:
